# Generated by Django 2.2.8 on 2020-03-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codices', '0003_auto_20200328_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
