# Generated by Django 2.2.8 on 2020-03-29 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codices', '0004_instructor_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CI', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('fechaNacimiento', models.DateField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
