# Generated by Django 2.2.8 on 2020-03-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codices', '0007_auto_20200329_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='CI',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fechaNacimiento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.IntegerField(blank=True),
        ),
    ]
