# Generated by Django 2.2.8 on 2020-03-31 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codices', '0010_auto_20200331_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='fechaFin',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='fechaInicio',
        ),
    ]
