# Generated by Django 2.2.8 on 2020-03-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codices', '0011_auto_20200331_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Deportes', 'Deportes'), ('Tecnología', 'Tecnología'), ('Arte', 'Arte'), ('Educación', 'Educación')], max_length=10)),
                ('costo', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual')], max_length=10)),
                ('descripcion', models.CharField(max_length=1000)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cursos',
        ),
    ]
